%!Rnw root = ../../Main.Rnw

% \chapter{Location and Spread}
\chapter{Descriptive Statistics}
\label{chap:ch3}

\section{Objectives}

After completing this part, students should be able to:

\fbox{\parbox{14cm}{
\begin{itemize}
\item Explain the concept of measures of central tendency and interpret the \\ information they provide.
\item Calculate, describe and compare the commonly used measures of central \\ tendency: mean, \textit{$\bar{X}$} and median, \textit{MED}.
\item Understand other measures of central tendency.
\item Select appropriate measure of central tendency based on the
level of \\ measurement and characteristics of the data (distribution).
\item Explain the concept of measures of spread and the information they convey.
\item Compute and explain sample standard deviation, (\textit{SD}).
\end{itemize}
}}

\section{Estimates of Center}

Suppose that a random sample of two-bedroom apartments in the Kalamazoo area yields the following data on monthly rent:

\$635, \$525, \$500, \$800, \$650, \$750, \$555, \$500, \$670, \$675

How much would we say is the average rent for two-bedroom apartments in Kalamazoo?  In this chapter, we will discuss the sample average and several alternatives to the average when estimating `average value' in a population.

\subsection{The Sample Mean}

The sample mean is the statistical term for `average of the sample.'  For the example above, the sample mean (denoted $\bar{X}$) is:

$$ \bar{X} = \frac{635+525+500+800+650+750+555+500+670+675}{10} = \$626 $$

so that the average rent in Kalamazoo may be estimated as \$626.  Note that this is an \textit{estimate} based on a \textit{sample}.  Therefore, it is subject to \textit{sampling error}.   Sampling error means that due to the luck of the draw, the sample average likely missed the true population average.  More precisely, the two-word term `sampling error' refers to $| \bar{X} - \mu |$,  the distance by which the \textit{sample} average $\bar{X}$  misses the population average  $\mu$.

The advantages of the sample mean:

\begin{itemize}
\item It is easy to understand and simple calculate.
\item It is based on all the values.
\item It is not based on the position in the series.
\end{itemize}

The disadvantage of the mean:

\begin{itemize}
\item It is always affected by outliers, which are relatively small and/or relatively large data values.
\end{itemize}

\subsection{The Sample Median}

There are alternative ways to estimate average rent if we want to avoid the effect of outliers.  We can determine the sample median, instead of the sample mean.  We have discussed the sample median (denoted MED) earlier in Chapter 1.  It is computed as follows.

\begin{enumerate}
\item Let $n$ represent the total number of observations.
\item Order the $n$ observations from smallest to largest.
\item Then calculate $0.50(n + 1)$ to locate the middle value of the dataset.
\item If $0.50(n + 1)$ is an integer, then MED is the $0.50(n + 1)th$ ordered observation.
\item If $0.50(n + 1)$ is not an integer, then MED is the average of the two adjacent ordered observations.
\item There are $n = 10$ observations in our rental data.  We first order them from smallest to largest.
\end{enumerate}

$$ 500, 500, 525, 555, 635, 650, 670, 675, 750, 800 $$

Now, $0.50(n + 1) = 0.50(10 + 1) = 5.5$.  Since this is not an integer, we average the $5^{th}$ and $6^{th}$ largest observations:

$$MED = \frac{(635 + 650)}{2} = \$642.50$$

The advantage of the median is that it is more robust than the mean, i.e., the median is not as affected by extreme values (outliers).

\subsection{The Trimmed Mean}

Since the mean uses all observations in the calculation, it can be strongly affected by outlying small and large values.  What happens to the mean when the smallest value \$500 is replaced by \$400?  It will become smaller.  What happens to the median?  It remains unchanged.

The trimmed mean is a compromise estimator that looks a lot like a mean but is less sensitive to extreme values.  The 10\%-trimmed mean removes the lowest 10\% and highest 10\% of the data, then take the sample mean of the remaining data.  In the rental example, 10\% of the data is one observation. We remove the lowest
observation (\$500) and the largest observation (\$800), and take the mean of the remaining eight observations:

$$\bar{X} = \frac{635+525+650+750+555+500+670+675}{10} = \$620$$

What if 10\% of the data is not an integer?  For example, if $n = 23$, then 10\% of n is 2.3.  Since we cannot remove 2.3 observations, we will remove three observations from each end (to ensure at least 10\% protection) and take the average of the middle 17 observations.


\section{Estimate of Spread (or Uncertainty or Variation)}

Recall the data on the monthly rent of two bedroom apartments in the Kalamazoo area:

$$ 500, 500, 525, 555, 635, 650, 670, 675, 750, 800 $$

If a future student asked us ``What should a two-bedroom apartment cost us in rent?'' how should we reply? Knowing that the data averages \$626, we might say something like ``Around \$626, give or take $\dots$(?).''   This second number, the give or take, is important because it says how much uncertainty there is in our guess.  In other words, the student's rent will probably miss \$626, but by how much?   We will get to the answer in a minute.   
For a second example, if we were going to San Francisco for a couple of days in August, and we want to know what clothes to bring, it is not enough to know that the average temperature is 68 degrees.  If it was 68 degrees, give or take 15 degrees, then we will need a sweater.  If it is 68 degrees, give or take 30 degrees, we might need a winter coat.

Variation presents itself everywhere.  Consider weight loss.  The 77 subjects in the Atkins group lost an average of 10.5 pounds `give or take' 15 pounds.  Compare this to an average of 3.5 pounds for the Zone diet `give or take' 14 pounds. How about in bowling?  In his first seven games in a tournament in Indiana, Walter Ray Williams Jr. averaged 228, `give or take' 34.   Notice how the `give or take' number seems to complete the description.

In this chapter, we will discuss the sample standard deviation, which is typically used as the ‘give or take’ number to describe spread in a group of numbers.

\subsection{The Sample Standard Deviation}

The standard deviation (or SD) is computed using a series of steps:
\begin{enumerate}
\item Compute the mean.
\item Subtract mean from each observation. These are the deviations from the mean or "Deviations".
\item Square the deviations from the mean. These are the "Squared Deviations".
\item Take the sum of squared deviations, this is called the "Sum of Squares" or \textit{SS}.
\item Compute SD using the equation: $$SD=\sqrt{\frac{SS}{n-1}}$$ where \textit{n} is the number of observations.
\end{enumerate}

The table below shows the computations for the monthly rent data. Notice in the last row that the sum of the deviations from the mean is 0. This will always be the case for the sum of deviations from the mean.

%\vspace{2cm}

<<label=LBL3a, results="asis", echo=FALSE>>=
  rent31 <- c(635,525,500,800,650,750,555,500,670,675)
  mn31   <- mean(rent31)
  diff31 <- rent31 - mn31
  SS31   <- diff31^2
  sum31  <- numeric(3)
  sum31[1] <- sum(rent31)
  sum31[2] <- sum(diff31)
  sum31[3] <- sum(SS31)
  tbl31 <- cbind(rent31, diff31, SS31)
  tbl32 <- rbind(tbl31, sum31)
  colnames(tbl32) <- c( "Rent", "Deviations", "Squared Deviations")
  rownames(tbl32) <- c('1','2','3','4','5','6','7','8','9','10','Sum')
  xtable(tbl32, digits=0)
  tmp31 <- sprintf("%.1f", sqrt(sum31[3]/9))
  tmp32 <- sum31[3]
@

$$ SD = \sqrt{ \frac{ SS}{n - 1}} = \sqrt{ \frac{ \Sexpr{tmp32}}{9}} \approx \Sexpr{tmp31} $$

It is helpful to get a feel for the numbers in the second column.  The first value 9 says that `635 is nine above average'.  The next number -101 says that `525 is 101 below average.'  Ignoring signs, the numbers in the second column represent the `give or take' from the average.  To get the actual SD, we take the Sum of Squares and divide by $(n - 1)$, and last, of all take the square root of that answer.  It gives us a final SD of 104.158.  We say that monthly rent averages \$626, `give or take' \$104.

Look at the second column again.  Ignoring signs, these are the distances from the average.  Which rental is closest to the average? The answer is \$635, which missed by 9. Which rental is farthest from the average?  \$800, which missed by 174.
What is the average `size of the miss?'  It should be somewhere between the smallest and largest, right?  It is how we interpret the SD: ``On the average, the monthly rentals miss the mean by \$104.''

Taken together, the mean and SD allow comparison of both relative size and spread of two groups of numbers.  In the professional bowling tournament in Indiana that he won in November of 2008, here are Walter Ray Williams Jr.'s first seven  games and last seven games (including the final):

% Requires the booktabs if the memoir class is not being used
\begin{table}[htbp]
   \centering
   %\topcaption{Table captions are better up top} % requires the topcapt package
   \begin{tabular}{@{} | lccc | @{}} \hline
      Games &  & Mean & SD \\ \hline
      First seven & 163,231,224,238,279,239,226 & 228.6 & 34.3 \\
      Last seven  & 246,244,247,248,237,258,246 & 246.6 & 6.2 \\ \hline
   \end{tabular}
   % \caption{Remember, \emph{never} use vertical lines in tables.}
   % \label{tab:booktabs}
\end{table}

What do the mean and SD tell us?  He averaged higher in the end but was also more consistent with a give-or-take of only 6 points!  His earlier games had more massive swings: from a low of 163 to a high of 279, resulting in the SD of 34.

\subsection{Effect of Multiplication and Addition by a Constant}

Recall that monthly rent for apartments average \$626 with an SD of \$104.  If the student plans to get a roommate and pay only half the rent, how much does he expect to pay?  If we are thinking of dividing both numbers by two, i.e., \$313 give or take \$52, this is correct.

\begin{center}
Original rent: $ 626 \pm 104 $ \hspace{2cm}	Half the rent: $ 313 \pm 52 $
\end{center}

Now suppose that the student does not plan to get a roommate, but his parents have agreed to contribute \$100 to rent each month.  How much does the student expect to pay after a subsidy of \$100?  If we are thinking of subtracting \$100 from both numbers, i.e., \$426 `give or take' \$4, there is an error in our thinking.  Here the SD remains the same, i.e.,

\begin{center}
Original rent: $ 626 \pm 104 $ \hspace{2cm} Subsidized rent: $ 526 \pm 104 $
\end{center}

If we are not convinced, consider the data itself on the following table.

\fbox{\parbox{14cm}{In general, when the data is \textbf{multiplied or divided by a positive constant}, the \textbf{same thing happens} to both the average and the SD}}


<<label=LBL3b, results="asis", echo=FALSE>>=
  tmp33 <- c(635,525,500,800,650,750,555,500,670,675)
  rent31 <- tmp33 / 2
  mn31   <- mean(rent31)
  diff31 <- rent31 - mn31
  SS31   <- diff31^2
  sum31  <- numeric(3)
  sum31[1] <- sum(rent31)
  sum31[2] <- sum(diff31)
  sum31[3] <- sum(SS31)
  tbl31 <- cbind(rent31, diff31, SS31)
  tbl32 <- rbind(tbl31, sum31)
  colnames(tbl32) <- c( "Rent", "Deviations", "Squared Deviations")
  rownames(tbl32) <- c('1','2','3','4','5','6','7','8','9','10','Sum')
  xtable(tbl32, digits=1, caption="Calculating the SD when rent is DIVIDED BY 2")
  tmp31 <- sprintf("%.2f", sqrt(sum31[3]/9))
  tmp32 <- sum31[3]
@

$$ SD = \sqrt{ \frac{ SS}{n - 1}} = \sqrt{ \frac{ \Sexpr{tmp32}}{9}} \approx \Sexpr{tmp31} $$

\newpage

\fbox{\parbox{14cm}{ In general, when we add or subtract a \textbf{constant} to the data, the same thing happens to the average, but the \textbf{SD remains unchanged.}}}

  <<label=LBL3c, results="asis", echo=FALSE>>=
  tmp34 <- c(635,525,500,800,650,750,555,500,670,675)
  rent31 <- tmp34 - 100
  mn31   <- mean(rent31)
  diff31 <- rent31 - mn31
  SS31   <- diff31^2
  sum31  <- numeric(3)
  sum31[1] <- sum(rent31)
  sum31[2] <- sum(diff31)
  sum31[3] <- sum(SS31)
  tbl31 <- cbind(rent31, diff31, SS31)
  tbl32 <- rbind(tbl31, sum31)
  colnames(tbl32) <- c( "Rent", "Deviations", "Squared Deviations")
  rownames(tbl32) <- c('1','2','3','4','5','6','7','8','9','10','Sum')
  xtable(tbl32, digits=1, caption="Calculating the SD when rent is reduced by 100 dollars")
  tmp31 <- sprintf("%.2f", sqrt(sum31[3]/9))
  tmp32 <- sum31[3]
@


$$ SD = \sqrt{ \frac{ SS}{n - 1}} = \sqrt{ \frac{ \Sexpr{tmp32}}{9}} \approx \Sexpr{tmp31} $$



\subsection{Risk ratio and odds ratio}   %%%%%%%%%%%%%%

 In clinical studies, statisticians frequently take ratios of proportions or probabilities (instead of differences).  There are several reasons for this idea.  Sometimes, the disease or medical event of interest is quite rare, i.e., $p_1 = 0.0008$.  If a new treatment reduces the probability of getting the disease to 0.0006, the difference in probabilities is quite small and hard to assess $((p_1 - p_2) = 0.0002)$.  In the meantime, the ratio $ \frac{p_2}{p_1} = \frac{0.0006}{0.0008} = 0.75 $ means that the risk of getting the disease under the new treatment has been reduced by 25\%.

A technical reason for using ratios is that a ratio can control for other variables such as age and race.

\subsection{Risk ratio}

Following is the abstract of the study ``Safety and Efficacy of a Recombinant Hepatitis E Vaccine.''  % \citep{shrestha2007}

\subsubsection{Background}

Hepatitis E virus (HEV) is a significant cause of viral hepatitis.  We evaluated
the safety and efficacy of an HEV recombinant protein (rHEV) vaccine in a phase
2, randomized, double-blind, placebo-controlled trial.

\subsubsection{Methods}

In Nepal, we studied 2000 healthy adults susceptible to HEV infection who were randomly assigned to receive three doses of either the rHEV vaccine or placebo at months 0, 1, and 6. Active (including hospital) surveillance was used to identify acute hepatitis and adverse events. The primary endpoint was the development of hepatitis E after three vaccine doses.

\subsubsection{Results}

A total of 1794 subjects (898 in the vaccine group and 896 in the placebo group) received three vaccine doses; researchers followed the total vaccinated cohort for a median of 804 days.  After three vaccine doses, hepatitis E developed in 69 subjects, of whom 66 were in the placebo group.  The vaccine efficacy was 95.5\% (95\% confidence interval [CI], 85.6 to 98.6).  In an intention-to-treat analysis that included all 87 subjects in whom hepatitis E developed after the first vaccine dose, nine subjects were in the vaccine group, with a vaccine efficacy of 88.5\% (95\% CI, 77.1 to 94.2).  Among subjects in a sub-group randomly selected for analysis of injection-site findings and general symptoms (reactogenicity sub-group) during the 8-day period after the administration of any dose, the proportion of subjects with adverse events was similar in the two study groups, except that injection-site pain was increased in the vaccine group ($p = 0.03$).

\subsubsection{Conclusion}

In a high-risk population, the rHEV vaccine was effective in the prevention of
hepatitis E.

The data given in the `Results' part of the abstract may be summarized as follows.

\begin{table}[ht]
\centering
\begin{tabular}{@{} cccc @{}} \hline
 & \multicolumn{2}{c}{hepatitis E} \\
 & Yes & No & Total \\ \hline
 Vaccine & 3 & 895 & 898 \\
 Placebo  & 66 & 830 & 896 \\ \hline
 \end{tabular}
 \end{table}

We may present data for comparing proportions in a 2 by 2 table.

\begin{table}[ht]
\centering
\begin{tabular}{@{} cccc @{}} \hline
 & \multicolumn{2}{c}{Disease} \\
 & Yes & No & Total \\ \hline
 Exposure & a & b & $a + b$ \\
 No Exposure  & c & d & $c + d$ \\ \hline
 \end{tabular}
 \end{table}

The risk ratio also called the relative risk is the ratio of probabilities

\begin{equation*}
  RR = \frac{ \frac{P(Disease)}{Exposure}}{ \frac{P(Disease)}{No Exposure} } = \frac{ \frac{a}{a + b}}{ \frac{c}{c + d} } = \frac{p_1}{p_2}
\end{equation*}

For our example, we can define and calculate the risk ratio as

\begin{equation*}
  RR = \frac{ \frac{P(Disease)}{Exposure}}{ \frac{P(Disease)}{No Exposure} } = \frac{ \frac{3}{898}}{ \frac{66}{896} } = \frac{0.00334}{0.07366} = 0.045
\end{equation*}

It means that getting the vaccine reduces our risk to only 4.5\% of the original, or has 95.5\% efficacy.

% \subsection{A 95\% confidence interval for risk ratio}
% 
% We write the confidence interval formulas for the natural logarithm of RR.  Consider a 2 by 2 table as before.
% 
% \begin{table}[ht]
% \centering
% \begin{tabular}{@{} cccc @{}} \hline
%  & \multicolumn{2}{c}{Disease} \\
%  & Yes & No & Total \\ \hline
%  Exposure & a & b & $a + b$ \\
%  No Exposure  & c & d & $c + d$ \\ \hline
%  \end{tabular}
%  \end{table}
% 
% We will calculate the confidence interval for RR in 4 steps.
% 
% \begin{enumerate}
% \item Calculate the \textbf{natural log (ln)} of the risk ratio:
% $$ ln(RR) = ln \left( \frac{ \frac{a}{a + b}}{ \frac{c}{c + d} } \right) $$
% 
% \item Calculate the standard error of ln(RR) as follows:
% 
% \begin{equation*}
%    SE_{ln(RR)} = \sqrt{ \frac{1}{a} + \frac{1}{c} - \frac{1}{a + b} - \frac{1}{c + d}}
% \end{equation*}
% 
% \item A 95\% confidence interval for ln(RR) is given by
% 
% \begin{equation*}
%   [ ln(RR) - 1.96 (SE), ln(RR) + 1.96 (SE) ]
% \end{equation*}
% 
% \item Finally, a 95\% confidence interval for RR is given by
% 
% \begin{equation*}
%   \Big[ e^{ln(RR) - 1.96 (SE)}, e^{ln(RR) + 1.96 (SE)} \Big]
% \end{equation*}
% 
% \end{enumerate}
% 
% Returning to our example,
% 
% \begin{enumerate}
% \item
% \begin{equation*}
% ln(RR) = ln(0.045) = -3.101
% \end{equation*}
% 
% \item
% \begin{equation*}
% SE_{ln(RR)} = \sqrt{ \frac{1}{3} + \frac{1}{66} - \frac{1}{898} - \frac{1}{896}} = \sqrt{0.3462} = 0.5884
% \end{equation*}
% 
% \item
% \begin{equation*}
%  [ -3.101 - 1.96(0.5884), -3.101 + 1.96(0.5884) ] = [ -4.254, 1.948]
% \end{equation*}
% 
% \item
% \begin{equation*}
%   \Big[ e^{-4.254}, e^{-1.948} \Big] = [ 0.014, 0.143 ]
% \end{equation*}
% 
% \end{enumerate}
% 
% With 95\% confidence, the risk of getting hepatitis with the vaccine is only 1.4\% to 14.3\% of placebo.  It means that the vaccine reduces our risk by as low as 85.7\% or as high as 98.6\%.  Now read the Results section of the abstract again.  They say ``The vaccine efficacy was 95.5\% (95\% confidence interval [CI], 85.6 to 98.6).''  The two sets of the numbers match, (slight discrepancy due to rounding error.)

\subsection{Odds ratio}

The odds of an event occurring is

\begin{equation*}
  Odds = \frac{ \texttt{Probability that event occurs}}{\texttt{Probability that event doesn't occur}} = \frac{p}{q}
\end{equation*}

For example, if you win a game a 20\% of the time ($p = 0.20$), then our odds of winning is $( \frac{0.20}{0.80}) = \frac{1}{4}$.  We say that we have a \textit{1-in-4} odds of winning, or we win once for every four times we lose.  If we win 80\% of the time, the odds are $\frac{0.80}{0.20} = 4$. It means we have \textit{4-in-1} odds of winning, or we win four times for every one time we lose.  Here is a table of odds corresponding to various probabilities.

\begin{table}[ht]
\centering
\begin{tabular}{@{} cc @{}} \hline
Probability & Odds \\ \hline
0.10 & 1/9 = 0.11 \\
0.20 & 1/4 = 0.25 \\
0.50 & 1/1 = 1.00 \\
0.80 & 4/1 = 4.00 \\
0.90 & 9/1 = 9.00 \\ \hline
\end{tabular}
\end{table}

Unlike probabilities, odds can be greater than 1.  The odds ratio is just the ratio of two odds (usually for comparing two groups).

\begin{equation*}
  Odds Ratio = \frac{ \texttt{Odds of Group 1}}{\texttt{Odds of Group 2}} = \frac{ \frac{p_1}{q_1}}{ \frac{p_2}{q_2}}
\end{equation*}

Returning to the hepatitis E study, recall the disease occurrence data:

\begin{table}[ht]
\centering
\begin{tabular}{@{} cccc @{}} \hline
 & \multicolumn{2}{c}{hepatitis E} \\
 & Yes & No & Total \\ \hline
 Vaccine & 3 & 895 & 898 \\
 Placbo  & 66 & 830 & 896 \\ \hline
 \end{tabular}
 \end{table}

The disease rate for each group is

\begin{equation*}
  \texttt{Odds(Hepatitis|Placebo)} = \frac{0.07366}{(1 - 0.07366)} = 0.07952
\end{equation*}

\begin{equation*}
  \texttt{Odds(Hepatitis|Vaccine)} = \frac{0.00334}{(1 - 0.00334)} = 0.00335
\end{equation*}

\begin{equation*}
  \texttt{Odds Ratio} = \frac{\texttt{Odds(Hepatitis|Placebo)}}{\texttt{Odds(Hepatitis|Vaccine)}} = \frac{0.07952}{0.00335} = 23.7
\end{equation*}

We say that ``the odds of getting hepatitis is 24 times greater if we remain unvaccinated.''

Odds ratios are generally easier to interpret if they are more significant than one.  We can always ensure this by choosing which group to put in the numerator, i.e., the one with more substantial odds.

It is essential to understand that the odds ratio is not a ratio of likelihood or probabilities.  If the disease rates for men and women are 0.80 and 0.40, respectively, then the odds ratio is

\begin{equation*}
   \frac{ \frac{0.80}{0.20}}{ \frac{0.40}{0.60}} = 6.00
\end{equation*}

In this example, men are twice as likely to get the disease but have six times the odds.

% \subsection{A 95\% confidence interval for odds ratio}
% 
% We write the confidence interval formulas for odds ratios (OR) for the natural logarithm, similarly to risk ratios.  Consider a 2 by 2 table as before.
% 
% \begin{table}[ht]
% \centering
% \begin{tabular}{@{} cccc @{}} \hline
%  & \multicolumn{2}{c}{Disease} \\
%  & Yes & No & Total \\ \hline
%  Exposure & a & b & $a + b$ \\
%  No Exposure  & c & d & $c + d$ \\ \hline
%  \end{tabular}
%  \end{table}
% 
% The odds of disease occurrence in the exposed group is $\Big[ \frac{ \frac{a}{a + b}}{ \frac{b}{a + b}} \Big] = \frac{a}{b} $.  Similarly, the odds in the unexposed group is $\frac{c}{d}$.  Hence, the odds ratio of disease occurrence is
% 
% \begin{equation*}
%   \texttt{OR} = \frac{\texttt{Odds(Disease|Exposed)}}{\texttt{Odds(Disease|Not Exposed)}} = \frac{a/b}{c/d} = \frac{p_1 / q_1}{p_2 / q_2} =\frac{p_1 \times q_2}{p_2 \times q_1}= \frac{ p_1 \times (1- p_2)}{ p_2 \times (1 - p_1)}
% \end{equation*}
% 
% If $OR < 1$, we can put the `not exposed' group in the numerator, so that $OR > 1$  (the resulting odds ratio should, of course, be interpreted accordingly).  In our hepatitis example, we can use the following table:
% 
% \begin{table}[ht]
% \centering
% \begin{tabular}{@{} cccc @{}} \hline
%  & \multicolumn{2}{c}{hepatitis E} \\
%  & Yes & No & Total \\ \hline
%  Placebo  & 66 & 830 & 896 \\
%  Vaccine & 3 & 895 & 898 \\
%   \hline
%  \end{tabular}
%  \end{table}
% 
% and get $OR = ((66)(895))/((830)(3)) = 23.7$ (``Placebo group has 24 times the odds of getting hepatitis''). If we use
% 
% \begin{table}[ht]
% \centering
% \begin{tabular}{@{} cccc @{}} \hline
%  & \multicolumn{2}{c}{hepatitis E} \\
%  & Yes & No & Total \\ \hline
%  Vaccine & 3 & 895 & 898 \\
%  Placebo  & 66 & 830 & 896 \\
%   \hline
%  \end{tabular}
%  \end{table}
% 
% then $OR = (3)(830)/(66)(895) = 0.04$ (``Vaccine group has 0.04 times the odds of getting hepatitis'').
% 
% In either case, we will calculate the confidence interval for odds ratio in 4 steps.
% 
% \begin{enumerate}
% \item Calculate the natural log of the odds ratio:
% \begin{equation*}
%   ln(OR) = ln \Big( \frac{a \times d}{b \times c} \Big)
% \end{equation*}
% 
% \item	Calculate the standard error of ln(OR) as follows:
% \begin{equation*}
%   SE_{ln(OR)} = \sqrt{ \Big( \frac{1}{a} + \frac{1}{b} + \frac{1}{c} + \frac{1}{d} \Big)}
% \end{equation*}
% 
% \item A 95\% confidence interval for ln(OR) is given by
% \begin{equation*}
%   [ ln(OR) - 1.96(SE), ln(OR) + 1.96(SE)]
% \end{equation*}
% 
% \item Finally, a 95\% confidence interval for OR is given by
% \begin{equation*}
%    e^{ln(OR) - 1.96(SE)}, e^{ln(OR) + 1.96(SE)}
% \end{equation*}
% 
% \end{enumerate}
% 
% Returning to the hepatitis E study, recall the disease occurrence data:
% 
% \begin{table}[ht]
% \centering
% \begin{tabular}{@{} cccc @{}} \hline
%  & \multicolumn{2}{c}{hepatitis E} \\
%  & Yes & No & Total \\ \hline
%  Placbo  & 66 & 830 & 896 \\
%  Vaccine & 3 & 895 & 898 \\
%   \hline
%  \end{tabular}
%  \end{table}
% 
% The odds ratio of getting hepatitis is
% 
% \begin{equation*}
%   \texttt{Odds Ratio} = \frac{\texttt{Odds(Hepatitis|Placebo)}}{\texttt{Odds(Hepatitis|Vaccine)}} = \frac{66 \times 895}{3 \times 830} = 23.7
% \end{equation*}
% 
% so that
% 
% \begin{enumerate}
% \item
% \begin{equation*}
%   ln(OR) = ln(23.7) = 3.165
% \end{equation*}
% 
% \item
% \begin{equation*}
%   SE_{ln(OR)} = \sqrt{ \frac{1}{66} + \frac{1}{830} + \frac{1}{3} + \frac{1}{895}   } = \sqrt{0.3508} = 0.5923
% \end{equation*}
% 
% \item
% \begin{equation*}
%  [3.165-1.96 (0.5923), 3.165+1.96 (.5923)] = [2.004, 4.326]
% \end{equation*}
% 
% \item
% \begin{equation*}
%   [ e^{2.004}, e^{4.326} ] = [ 7.419, 75.641]
% \end{equation*}
% \end{enumerate}
% 
% With 95\% confidence, the odds of unvaccinated subjects getting hepatitis is between 7 and 76 times greater than vaccinated subjects.

\section{Key Words}

\fbox{\parbox{14cm}{

\begin{itemize}
    \item odds
    \item odds ratio
    \item sample mean
    \item sample median
    \item trimmed mean
    \item sample standard deviation
\end{itemize}
}}

%%%%%%%%%%%%%%%%%%%%%%%%%% Exercises %%%%%%%%%%%%%%%%%%%%
\twocolumn

\section{}

\begin{exercises}
  \begin{exercise} % 1

The carbon monoxide \\ measures (in mgs) are given on 25 brands of  cigarettes.

13.6    16.6    23.5    10.2     5.4     15.0     9.0    12.3    16.3   15.4
13.0    14.4    10.0    10.2     9.5      1.5    18.5    12.6    17.5    4.9
15.9     8.5    10.6    13.9    14.9

Calculate the

\begin{enumerate}
\item mean
\item median
\item 10\% trimmed-mean
\item standard deviation
\item mean and standard deviation (in \\ grams)
\end{enumerate}

	\end{exercise}
	\begin{solution}  % 1
<<label=LBL3-1, results='asis', echo=FALSE>>=
  DT1 <- c(13.6,16.6,23.5,10.2,5.4,15.0,9.0,12.3,16.3,15.4,
13.0,14.4,10.0,10.2,9.5,1.5,18.5,12.6,17.5,4.9,
15.9,8.5,10.6,13.9,14.9)
  tmp3a <- sort(DT1)

  mn1 <- sprintf('%.1f', mean(DT1))
  md1 <- sprintf('%.1f', median(DT1))
  tr1 <- sprintf('%.1f', mean(tmp3a[4:22]))
  sd1 <- sprintf('%.2f', sd(DT1))
  mn2 <- sprintf('%.4f',mean(DT1)/1000)
  sd2 <- sprintf('%.5f',sd(DT1)/1000)
  mod1 <- 35
@

	Compute the mean, median, $\dots$ for carbon monoxide:
  \begin{enumerate}
  \item mean = \Sexpr{mn1}
  \item median = \Sexpr{md1}
  \item trimmed mean = \Sexpr{tr1}
  \item SD = \Sexpr{sd1}
  \item mean = \Sexpr{mn2} and standard deviation \Sexpr{sd2} in  grams
	\end{solution}

%   \begin{exercise} % 2
% 
%   Calculate the median of \\ pairwise average for the first 6 observations which are listed below:
% 
% 13.6    16.6    23.5    10.2     5.4     15.0

 	% \end{exercise}
 	% \begin{solution}  % 2
 	%
 	%
 	% The third value must be 22 so that the average is 20 for all three quizzes.
 	% \end{solution}

  \begin{exercise} % 2

  Daily high temperature for a given day are provided for the past 10 \\ years:

\begin{tabular}{@{} ccccc @{}} \hline
2007 & 2008 & 2009 & 2010 & 2011 \\
59 & 50 & 49 & 13 & 41 \\ \hline
2012 & 2013 & 2014 & 2015 & 2016 \\
46 & 51 & 53 & 58 & 47 \\ \hline
\end{tabular}

Find the following statistics for \\ temperature:

\begin{enumerate}
\item range
\item mean
\item median
\item Remove the temperature of the year \\ 2010 from the data set and re-calculate the mean and compare it with part (2)? Is the mean closer to the median and why?
\end{enumerate}

   \end{exercise}
   \begin{solution} % 2

<<label=LBL3-2, result="asis", echo=FALSE>>=
  xdt1 <- c(59,50,49,13,41,46,51,53,58,47)
  tmp3b <- sort(xdt1)
  rng1  <- tmp3b[1]
  rng2  <- tmp3b[10]
  mn33  <- mean(tmp3b)
  md33  <- median(tmp3b)
  mn34  <- sprintf('%.1f', mean(tmp3b[2:10]) )
@

\begin{enumerate}
\item The range is from \Sexpr{rng1} to \Sexpr{rng2}
\item The mean is \Sexpr{mn33}
\item The median is \Sexpr{md33}
\item Removing the smallest value changes the mean to \Sexpr{mn34}.  The new value is closer to median because 13 is an outlier.
\end{enumerate}
  \end{solution}
 
   \begin{exercise} % 3

Joshua has been \\ working  on  programming  and updating a \\ Website for his  company for the past 12 \\ months. The following numbers represent the number of hours Joshua  has worked on this Website for each of the past 12 months:

24, 25, 31, 40, 48, 40, 36, 50, 38, 35 ,42, 112

\begin{enumerate}
\item Calculate the mean
\item Calculate the median
\item Decide if its symmetric, skewed to the right or to the left
\item Decide which measure of center \\ provides the most relevant information about the distribution? Why?
\end{enumerate}

\end{exercise}
\begin{solution}  % 3
<<label=LBL3-3, results="asis", echo=FALSE>>=
  dt3 <- c(24, 25, 31, 40, 48, 40, 36, 50, 38, 35 ,42, 112)
  mn1 <- mean(dt3)
  md1 <- median(dt3)
@

% \begin{enumerate}
% \item the mean is \Sexpr{mn1}
% \item the median is \Sexpr{md1}
% \item Decide if its symmetric, skewed to the right or to the left: the data is right skewed
% \item Decide which measure of center provides the most relevant information about the distribution? Why?  The median is the most relevant information because the data is right skewed.
% \end{enumerate}

\end{solution}



\begin{exercise} % 4

<<label=LBL3-4, results="asis", echo=FALSE>>=
  shape5 <- numeric(3)
  shape5[1] <- "Left skewed"
  shape5[2] <- "Symmetric"
  shape5[3] <- "Right skewed"
  DT5a <- c(86,175,157,282,38,211,497,246,393,198,
            146,176,220,224,337,180,182,185,396,264,
            251,76,42,149,65,93,423,188,203,105,
            653,264,321,180,151,315,185,568,829,203,
            98,15,180,325,341,353,229,55,239,124,
            249,364,198,250,40,571,400,55,236,137,
            400,195,38,196,40,124,338,61,286,135,
            292,262,20,90,135,279,290,244,194,350,
            131,88,61,229,597,81,398,20,277,193,
            169,264,121,166,246,186,71,284,143,188)

  SMP5a <- sample(x=DT5a, size=9, replace=TRUE)
  mn5   <- mean(SMP5a)
  md5   <- median(SMP5a)
  sd5   <- sd(SMP5a)
  if(mn5 == md5){shp5 <- 2}
  if(mn5 > md5){shp5 <- 3} else{shp5 <- 1}
  shp5a  <- shape5[shp5]
@

In a study of warp \\ breakage during the process of weaving \\ fabric (\textit{Technometrics}, 1982: 63).  Nine \\ specimens of yarn were tested.  The \\ number of cycles of strain to breakage was \\ determined for each yarn specimen, \\ resulting in the following  data:

\vspace{3mm}

{\small{
\Sexpr{SMP5a} 
}}


\begin{enumerate}
\item Calculate the mean
\item Calculate the median
\item Calculate the standard deviation
\item Decide if its distribution (symmetric, \\ skewed to the right or to the left)
\item Decide which measure of center \\ provides the most relevant information about the distribution? Why?
\end{enumerate}

\end{exercise}
\begin{solution}   % 4

\begin{enumerate}
\item $\bar{x} = \Sexpr{mn5}$
\item $\tilde{x} = \Sexpr{md5}$
\item $sd = \Sexpr{sd5} $
\item The distribution is \Sexpr{shp5a}
\item The median provided the most relevant information because to the extreme outlier.
\end{enumerate}

\end{solution}

% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% new exercises
% 
  \begin{exercise} % 5

  The weekly budgets for \\ groceries of six students are as follows: \\
\$30, \$35, \$40, \$28, \$35, \$25. \\ Compute for the mean and median and \\ choose the correct answer from the choices below:
	\begin{enumerate}
	\item mean = 188, median = 30
	\item mean = 32.167, median = 35
	\item mean= 32.167, median = 32.5
	\item mean= 188, median = 30
	\end{enumerate}

	\vspace{5mm}
    \framebox[5cm][l]{ Answer: }
	\end{exercise}
	\vspace{2mm}
	\begin{solution}   % 5

	Compute the mean, median, and mode for the weekly grocery budget
	mean = 32.167, median = 32.5

	\end{solution}

  \begin{exercise} % 6

  John got 16 and 22 on his two Stat 1600 quizzes.  What score must he have on his next quiz to have the mean of \\ exactly 20 for his three quizzes?
	\begin{enumerate}
	\item 20
	\item 22
	\item 18
	\item 24
	\end{enumerate}

	\vspace{5mm}
    \framebox[5cm][l]{ Answer: }
	\end{exercise}
	\vspace{2mm}
	\begin{solution}   % 6

	The third value must be 22 so that the average is 20 for all three quizzes.

	\end{solution}

  \begin{exercise} % 7

    The following table lists \\ the average number of cars per 1000 \\ population for eight nations. Compute the mean and median for these data.

% Requires the booktabs if the memoir class is not being used
% \begin{table}[htbp]
%  \centering
   %\topcaption{Table captions are better up top} % requires the topcapt package
  % \multicolumn{9}{c}{Time Lost due to Traffic Congestion}
  {\small{
   \begin{tabular}{@{} lc @{}} \hline  % Column formatting, @{} suppresses leading/trailing space
   Nation & cars per 1000 population \\ \hline
   United States & 820 \\
   Canada & 607 \\
   China & 83 \\
   Russia & 293 \\
   Japan & 591 \\
   Mexico & 275 \\
   Spain & 593 \\
   United Kingdom & 519 \\ \hline
   \end{tabular}
  }}
   % \caption{Source: http://www.nationmaster.com}
   % \label{tab:t3_9}
% \end{table}


  \begin{enumerate}
  \item Which is greater in value?
  \item Is there a positive skew in the data?
  \item How do you know?
  \end{enumerate}

  % \vspace{5mm}
  %   \framebox[5cm][l]{ Answer: }
  \end{exercise}
  % \vspace{2mm}
  \begin{solution}   % 7


<<result="asis", echo=FALSE>>=

xdt1 <- c(819.79, 607, 83, 293, 591, 275, 593, 519)
xsumm1 <- summary(xdt1)
@

    The mean is \Sexpr{xsumm1[4]}
    The median is \Sexpr{xsumm1[3]}
    %There is no mode since there are no duplicates.

{\bf{1. }} The greater value is the median (555).  {\bf{2. }} There is a negative skewness in the middle half the of the dataset.  (Refer to Figure 3.1.)

\begin{figure}[htbp] %  figure placement: here, top, bottom, or page
   \centering
   \includegraphics[width=6cm]{figure/f3_1-1.pdf}
   \caption{Boxplot of Cars per 1000}
   \label{fig:f3_1}
\end{figure}

{\bf{3. }} When we compare the median to the mean, we find the median (555) is greater the mean (472.6).  Therefore, we can say the the dataset is left skewed.

  \end{solution}

  \begin{exercise} % 8

You are a researcher for a mid-sized city. You collected six types of \\ variables from a random sample of students from a large university.  These variables include:

  \begin{enumerate}
  \item their region of birth of country
  \item the extent they support marijuana \\ legalization (7=strong, 4=neutral, \\ 1=weak)
  \item the weekly amount of money spent on cafeteria food
  \item number of movies they watched per \\ week
  \item quality of cafeteria food at their university (10=excellent, 0=bad)
  \item religious affiliation.
  \end{enumerate}

Select the  appropriate measures of central \\ tendency for each variable.


% \end{minipage}

% \vspace{1cm}
%     \framebox[5cm][l]{ Answer: }

  \end{exercise}
  \begin{solution}   % 8

  {\bf{(1. )}} Mode  {\bf{(2. )}} Median  {\bf{(3. )}} Mean  {\bf{(4. )}} Mean  {\bf{(5. )}} Median  {\bf{(6. )}} Mode

  \end{solution}

%' \pagebreak
  \begin{exercise} % 9

% Requires the booktabs if the memoir class is not being used
\begin{table}[htbp]
   \centering
   \caption{Find appropriate measures of central tendency}
   %\topcaption{Table captions are better up top} % requires the topcapt package
   {\tiny{
   \begin{tabular}{@{} cccccc  @{}} \hline % Column formatting, @{} suppresses leading/trailing space
   Student & Birth  & Expense & Movies & Food & Religion \\ \hline
   a & West  & 43 & 4 & 6 & Cath. \\
   b & MW  & 51 & 3 & 5 & Other \\
   c & South  & 65 & 14 & 0 & Other \\
   d & South  & 52 & 0 & 10 & Prot. \\
   e & North  & 48 & 1 & 6 & Jew \\
   f & North  & 62 & 5 & 8 & Prot. \\
   g & MW  & 47 & 7 & 1 & None \\
   h & South  & 45 & 10 & 2 & Cath. \\
   i & North  & 39 & 14 & 7 & Prot. \\
   j & North  & 33 & 0 & 10 & Prot. \\ \hline
   \end{tabular}
   }}
   \label{tab:t3_3a}
\end{table}

  Using the dataset from Table 3.3, determine the value of the central tendency measures for each variable.

   % \framebox[5cm][l]{ Answer: }
  \end{exercise}
   \begin{solution}  % 9

     {\bf{Birth}} Mode=``North'';   {\bf{Expense}} Mean=48.5; {\bf{Movies}} Mean=5.8; {\bf{Food}} Median=6;  {\bf{Religion}} Mode=``Protestant''

   \end{solution}

% \newpage
  \begin{exercise} % 10

As a leader of a Kalamazoo social services agency that employs 20 staff members, you are concerned that your staff has an increased case load of clients \\ compared to 10 years ago.  The case load of each worker is reported in the following table (Table 3.4) for years 2005 and 2015.

% Requires the booktabs if the memoir class is not being used
\begin{table}[htbp]
   \centering
   \caption{Case Loads Comparison}
   %\topcaption{Table captions are better up top} % requires the topcapt package
   {\tiny{
   \begin{tabular}{@{} ccccccccccc  @{}} \hline % Column formatting, @{} suppresses leading/trailing space
   2005 & 50&64&55&64&60&53&56&50&51&45 \\ & 46&46&50&56&63&65&53&54&58&69 \\ \hline
   2015 & 57&47&46&59&59&50&57&52&41&66 \\ & 65&52&57&75&65&76&43&56&52&67 \\ \hline
   \end{tabular}

   \label{tab:t3_4a}
   }}
\end{table}

  Has the average case load increased, \\ decreased, or stayed the same?

   \vspace{2mm}
     \framebox[5cm][l]{ Answer: }
  \end{exercise}
  \vspace{2mm}
  \begin{solution} %10

<<results="asis", echo=FALSE>>=
        cl2005 <- c(50,	64,	55,	64,	60,	53,	56,	50,	51,	45,	46,	46,	50,	56,	63,	65,	53,	54,	58,	69)
        cl2015 <- c(57,	47,	46,	59,	59,	50,	57,	52,	41,	66,	65,	52,	57,	75,	65,	76,	43,	56,	52,	67)
        mn3a <- mean(cl2005)
        med3a <- median(cl2005)
        mn3b <- mean(cl2015)
        med3b <- median(cl2015)
@
The mean for 2005 is \Sexpr{mn3a}.
The median for 2005 is \Sexpr{med3a}.
The mean for 2015 is \Sexpr{mn3b}.
The median for 2015 is \Sexpr{med3b}.

  \end{solution}

  \begin{exercise} % 11

  The admissions \\ department at WMU gave 25 randomly selected freshmen a national prejudice survey.  The racial prejudice index scores  will be used in three years to see if higher education affects prejudice.

% Requires the booktabs if the memoir class is not being used
\begin{table}[htbp]
   \centering
   %\topcaption{Table captions are better up top} % requires the topcapt package
   {\small{
   \caption{Freshmen Racial Prejudice Index}
   \begin{tabular}{@{} ccccc  @{}} \hline % Column formatting, @{} suppresses leading/trailing space
   45 & 30 & 35 & 30 & 42 \\
   50 & 43 & 40 & 32 & 48 \\
   9  & 13 & 10 & 11 & 11 \\
   40 & 26 & 39 & 38 & 44 \\
   32 & 37 & 41 & 27 & 22 \\ \hline
   \end{tabular}

   \label{tab:t3_12}
   }}
\end{table}

  Calculate the mean and median scores of \\ these data from Table 3.5.

	\vspace{2mm}
    \framebox[5cm][l]{ Answer: }
	\end{exercise}
	\begin{solution}   % 11

	The mean is
	<<results="asis", echo=FALSE>>=
	e3dat7 <- c(45, 30, 35, 30,42, 50, 43, 40, 32, 48, 9, 13, 10, 11, 11, 40, 26, 39, 38, 44, 32, 37, 41, 27, 22)
	mean(e3dat7)
  @

	The median is
	<<results="asis", echo=FALSE>>=

	median(e3dat7)
  @

	\end{solution}

	  \begin{exercise} % 12

The same 25 students \\ completed the same survey during their senior  year.  Compute the mean and median for this second set of scores, and compare them to the scores from four years earlier.   What happened?

% Requires the booktabs if the memoir class is not being used
\begin{table}[htbp]
   \centering
   %\topcaption{Table captions are better up top} % requires the topcapt package
   {\small{
   \caption{Senior Racial Prejudice Index}
   \begin{tabular}{@{} ccccc  @{}} \hline % Column formatting, @{} suppresses leading/trailing space
   50 & 27 & 31 & 35 & 41 \\
   11 & 45 & 50 & 37 & 43 \\
   11 & 9  & 10 & 20 & 10 \\
   35 & 10 & 30 & 41 & 40 \\
   15 & 30 & 40 & 26 & 21 \\ \hline
   \end{tabular}
   }}

   \label{tab:t3_6a}
\end{table}

  Calculate the mean and median scores of \\ these data.

	\vspace{2mm}
    \framebox[5cm][l]{ Answer: }
	\end{exercise}
	\vspace{2mm}
	\begin{solution}   % 12

<<results="asis", echo=FALSE>>=
	e3dat8 <- c(50, 27, 31, 35, 41, 11, 45, 50, 37, 43, 11, 9, 10, 20, 10, 35, 10, 30, 41, 40, 15, 30, 40, 26, 21)

	mn38 <- mean(e3dat8)
	md38 <- median(e3dat8)
	rm(e3dat8)
@

  The mean is \Sexpr{mn38}, and the median is \Sexpr{md38}

	\end{solution}

	\begin{exercise} % 13

A local social service \\ agency has started a sex education course for teen girls.  The girls took a 20-question exam for general information about sex, anatomy and physiology upon entry and again after completing the course.  Table 3.7 has the listing of scores of a random sample of 15 \\ girls.

Calculate the mean and median of the pre and post test scores and comment on the results.

 % latex table generated in R 3.2.1 by xtable 1.7-4 package
 % Wed Sep  2 09:06:12 2015
\begin{table}[ht]
 \centering
 \caption{Pre and Post Test Results}

 {\small{
 \begin{tabular}{@{} rrrrr @{}}
   \hline
   case & posttest & pretest & difference \\
   \hline
    1 &  12 &   8 &   4 \\
      2 &  13 &   7 &   6 \\
      3 &  12 &  10 &   2 \\
      4 &  19 &  15 &   4 \\
      5 &   8 &  10 &  -2 \\
      6 &  17 &  10 &   7 \\
      7 &  12 &   3 &   9 \\
      8 &  11 &  10 &   1 \\
      9 &   7 &   5 &   2 \\
     10 &  12 &  15 &  -3 \\
     11 &  21 &  13 &   8 \\
     12 &   5 &   4 &   1 \\
     13 &  15 &  10 &   5 \\
     14 &  11 &   8 &   3 \\
     15 &  20 &  12 &   8 \\
    \hline
 \end{tabular}
 }}

 \label{tab:t3_14}
\end{table}

	\vspace{2mm}
    \framebox[5cm][l]{ Answer: }
	\end{exercise}
	\vspace{2mm}
	\begin{solution}  % 13


<<results="asis", echo=FALSE>>=
	pretest3 <- c(8,7,10,15,10,10,3,10,5,15,13,4,10,8,12)
	mn3a <-  mean(pretest3)
@

	The pretest mean is  \Sexpr{mn3a}

<<results="asis", echo=FALSE>>=
	med3a <- median(pretest3)
@
	The pretest median is \Sexpr{med3a}

<<results="asis", echo=FALSE>>=
	posttest3 <- c(12,13,12,19,8,17,12,11,7,12,20,5,15,11,20)
	mn3a <- mean(posttest3)
@
	The posttest mean is	\Sexpr{mn3a}

<<results="asis", echo=FALSE>>=
	med3b <- median(posttest3)
@
The pretest median is \Sexpr{med3b}

	\end{solution}

	\begin{exercise}   % 14

	The acidity or alkalinity of a solution is measured using pH.  A pH less than 7 is acidic; a pH greater than 7 is alkaline.  The following data represent the pH in samples of bottled water and tap water.

\begin{table}[ht]
 \centering

	{\small{             % \footnotesize{
	\caption{Source: Emily. McCarney, \\ Joliet College}
 \begin{tabular}{@{} rrcrr @{}}
     % \multicolumn{4}{c}{TAP    |    BOTTLED}  \hline
  % \multicolumn{2}{Tap} & | & \multicolumn{2}{Bottled} \hline
   Tap &  & | & Bottled  & \\ \hline
   7.64 & 7.45 & | & 5.15 & 5.28 \\
   7.45 & 7.10 & | & 5.09 & 5.26 \\
   7.47 & 7.56 & | & 5.26 & 5.13 \\
   7.50 & 7.47 & | & 5.20 & 5.26 \\
   7.68 & 7.52 & | & 5.02 & 5.21 \\
   7.69 & 7.47 & | & 5.23 & 5.24 \\
    \hline
 \end{tabular}
 }}
   \label{tab:t3_15}
 \end{table}

\begin{enumerate}
 \item Calculate the mean  of the tap water.
 \item Determine the median of the tap water.
 \item Comment on the results.
\end{enumerate}
  \end{exercise}
%   \begin{solution}  % 14
%
%
%   \end{solution}

\begin{exercise}  % 15

The median age for \\ Black Americans (BA) is 30.9; for White \\ Americans (WA) is 42.3.

\begin{enumerate}
\item Based on this statement, give two reasons why this age disparity.
\item Does median age of BA say that BA die younger than WA? Why or why not?
\item Is it possible for BA and WA to die the same age, but have different median \\ ages?
\end{enumerate}

\end{exercise}
\begin{solution}  % 15

\begin{enumerate}
\item   1) less education, 2) less wealth, 3) poorer health, 4) racism 
\item Does median age of BA say that BA die younger than WA? Why or why not?  
\item Is it possible for BA and WA to die the same age, but have different median \\ ages?
\end{enumerate}
\end{solution}



\end{exercises}

\onecolumn
